namespace-packages = ["pdfminer"]

[lint]
extend-select = [
    "W",  # pycodestyle warnings
    "I",  # isort
    "TID"  # flake8 tidy imports
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"